### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by 127** [gabrimatic/restart#4]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: MissingPluginException(No implementation found for method restartApp on channel restart)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      Restart.restartApp (package:restart_app/restart_app.dart:9:8)
<asynchronous suspension>

**Comment by gabrimatic** [comment]
You have to stop your running app, run flutter pub get, and then rerun the app again.

**Comment by gabrimatic** [comment]
> I still get this exception even after killing the app, uninstalling it, run `flutter clean`, run `flutter pub get`, the run the app again from cold. This is on the iOS simulator

This package doesn't support iOS for now.
